apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: frontend-pipeline
  namespace: my-turn-app
spec:
  workspaces:
  - name: dependencies
    persistentVolumeClaim:
      claimName: pvc-frontend-dependencies
  params:
    - name: git
      type: git
  resources:
    - name: tag
      description: New tag version generate only after a unit test success execution.
    - name: backend-url
      description: Param needed to build the frontend layer that will consumes a unique backend url.
    - name: app-url
      description: Url used to execute the e2e tests over an actually deployed environment.
  tasks:
    - name: get-build-params
      taskRef:
        name: oc-get-route-url
      resources:
        outputs:
        - name: route-url
          resource: backend-url
    - name: unit-test-and-build
      taskRef:
        name: vue-unit-test-and-build
      inputs:
        params:
        - name: url
          value: "$(params.git.url)"
      resources:
        inputs:
        - name: backend-url
          resource: backend-url
          from:
          - get-build-params
        outputs:
        - name: tag
          resource: tag
      workspaces:
      - name: npm-modules
        workspace: dependencies
    - name: update-deploy
      taskRef:
        name: update-deploy-and-wait
      runAfter:
      - unit-test-and-build
      resources:
        inputs:
        - name: tag
          resource: tag
          from:
          - unit-test-and-build
        outputs:
        - name: frontend-url
          resource: app-url
    - name: test-e2e
      taskRef:
        name: vue-test-e2e
      runAfter:
      - update-deploy
      resources:
        inputs:
        - name: app-url
          resource: app-url
          from:
          - update-deploy
      workspaces:
      - name: npm-modules
        workspace: dependencies
