kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-frontend-dependencies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gold
status:
