apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: vue-e2e-test
spec:
  inputs:
    resources:
      - name: git
        type: git
  steps:
    - image: 'quay.io/rshop/toolchain-cli-alpine:master'
      name: clone-code
      resources: {}
      script: |
        git show-branch --current
        tree -L 1 ./frontend
      securityContext:
        runAsUser: 0
      workingDir: /workspace/git
    - image: 'quay.io/openshift/origin-cli:latest'
      name: get-app-url
      resources: {}
      script: |
        export PROTOCOLO=`if [ "$(oc get route frontend -o jsonpath='{

        .spec.tls.termination }')" != "" ]; then echo "https"; else echo "http";

        fi`

        echo "APP_URL=$PROTOCOLO://$(oc get route frontend -o jsonpath='{
        .spec.host

        }')" | tee .env.local
      workingDir: /workspace/git/frontend
    - image: 'quay.io/rshop/npm-alpine:master'
      name: test-lint-and-build
      resources: {}
      script: |
        npm install
        source .env.local
        npm run test:e2e-remote "$APP_URL"
      securityContext:
        runAsUser: 0
      workingDir: /workspace/git/frontend
  workspaces:
    - description: The node packages needed for this app
      mountPath: /workspace/git/frontend/node_modules
      name: npm-modules
