apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-frontend-image
spec:
  inputs:
    params:
      - default: oci
        description: 'The format of the built container, oci or docker'
        name: FORMAT
        type: string
      - default: 'true'
        description: >-
          Verify the TLS on the registry endpoint (for push/pull to a non-TLS
          registry)
        name: TLSVERIFY
        type: string
    resources:
      - name: git
        type: git
      - name: image
        type: image
  steps:
    - image: 'quay.io/rshop/toolchain-cli-alpine:v0.1'
      name: clone-code
      resources: {}
      script: |
        git show-branch --current
        tree -L 1 ./frontend
      workingDir: /workspace/git
    - image: 'quay.io/openshift/origin-cli:latest'
      name: get-backend-url
      resources: {}
      script: >
        export PROTOCOLO=`if [ "$(oc get route backend -o jsonpath='{
        .spec.tls.termination }')" != "" ]; then echo "https"; else echo "http";
        fi`

        echo "VUE_APP_API_URL=$PROTOCOLO://$(oc get route backend -o jsonpath='{
        .spec.host }')" | tee .env.local
      workingDir: /workspace/git/frontend
    - image: 'quay.io/rshop/npm-alpine:master'
      name: test-lint-and-build
      resources: {}
      script: |
        npm install
        npm run test:unit
        npm run lint
        npm run build
      workingDir: /workspace/git/frontend
    - command:
        - buildah
        - bud
        - '--format=$(inputs.params.FORMAT)'
        - '--tls-verify=$(inputs.params.TLSVERIFY)'
        - '--layers'
        - '-f'
        - Dockerfile
        - '-t'
        - $(inputs.resources.image.url)
        - .
      image: 'quay.io/buildah/stable:latest'
      name: build-image
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/git/frontend
    - command:
        - buildah
        - push
        - '--authfile=/root/.docker/config.json'
        - '--tls-verify=$(inputs.params.TLSVERIFY)'
        - $(inputs.resources.image.url)
        - 'docker://$(inputs.resources.image.url)'
      image: 'quay.io/buildah/stable:latest'
      name: push-image
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
        - mountPath: /root/.docker
          name: docker-config-volume
  volumes:
    - emptyDir: {}
      name: varlibcontainers
    - name: docker-config-volume
      secret:
        secretName: rshop-registry-auth
  workspaces:
    - description: The node packages needed for this app
      mountPath: /workspace/git/frontend/node_modules
      name: npm-modules
