apiVersion: v1
kind: List
items:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pvc-frontend-dependencies
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
  status:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pvc-backend-dependencies
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
  status:
