apiVersion: v1
kind: List
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineRun
  metadata:
    generateName: frontend-pipeline
    name: frontend-pipelinefllh8
    namespace: my-turn-app
    labels:
      tekton.dev/pipeline: frontend-pipeline
  spec:
    pipelineRef:
      name: frontend-pipeline
    serviceAccountName: pipeline
    workspaces:
    - name: dependencies
      persistentVolumeClaim:
        claimName: pvc-frontend-dependencies
  status:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineRun
  metadata:
    generateName: backend-pipeline
    name: backend-pipelinefllh8
    namespace: my-turn-app
    labels:
      tekton.dev/pipeline: backend-pipeline
  spec:
    pipelineRef:
      name: backend-pipeline
    serviceAccountName: pipeline
    workspaces:
    - name: dependencies
      persistentVolumeClaim:
        claimName: pvc-backend-dependencies
  status:
