apiVersion: v1
kind: List
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: source-repository
  spec:
    type: git
    params:
    - name: url
      value: https://gitlab.com/caio.dona/my-turn-app.git
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: config-repository
  spec:
    type: git
    params:
    - name: url
      value: https://gitlab.com/caio.dona/my-turn-app-configuration.git
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: frontend-image
  spec:
    type: image
    params:
    - name: url
      value: quay.io/rshop/my-turn-app-frontend
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: backend-image
  spec:
    type: image
    params:
    - name: url
      value: quay.io/rshop/my-turn-app-backend
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    name: frontend-pipeline
  spec:
    resources:
    - name: source-repo
      type: git
    - name: config-repo
      type: git
    - name: image
      type: image
    tasks:
    - name: unit-test-and-build-image
      resources:
        inputs:
        - name: git
          resource: source-repo
        - name: image
          resource: image
      taskRef:
        kind: Task
        name: build-frontend-image
      workspaces:
      - name: npm-modules
        workspace: dependencies
    - name: deploy-in-dev
      resources:
        inputs:
        - name: image
          resource: image
      params:
      - name: LAYER
        value: frontend
      - name: FLAGS
        value: '--insecure'
      runAfter:
      - unit-test-and-build-image
      taskRef:
        kind: Task
        name: deploy-with-argocd
    - name: e2e-test
      resources:
        inputs:
        - name: git
          resource: source-repo
      retries: 2
      runAfter:
      - deploy-in-dev
      taskRef:
        kind: Task
        name: vue-e2e-test
      workspaces:
      - name: npm-modules
        workspace: dependencies
    workspaces:
    - name: dependencies
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    name: backend-pipeline
  spec:
    resources:
    - name: source-repo
      type: git
    - name: config-repo
      type: git
    - name: image
      type: image
    tasks:
    - name: unit-test-and-build-image
      resources:
        inputs:
        - name: git
          resource: source-repo
        - name: image
          resource: image
      taskRef:
        kind: Task
        name: build-backend-image
      workspaces:
      - name: npm-modules
        workspace: dependencies
    - name: deploy-on-develop
      runAfter:
      - unit-test-and-build-image
      resources:
        inputs:
        - name: image
          resource: image
      params:
        - name: LAYER
          value: backend
        - name: FLAGS
          value: '--insecure'
      taskRef:
        kind: Task
        name: deploy-with-argocd
    - name: deploy-on-qa
      runAfter:
      - deploy-on-develop
      resources:
        inputs:
        - name: image
          resource: image
      params:
        - name: LAYER
          value: backend
        - name: FLAGS
          value: '--insecure'
        - name: ENVIRONMENT
          value: qa
      taskRef:
        kind: Task
        name: deploy-with-argocd
    workspaces:
    - name: dependencies
