apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: rshop-registry-auth
  type: Opaque
  data:
    config.json: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbk5vYjNBcmIyTndYMkoxYVd4a1pYSmZhVzFoWjJVNlFWTkpORWcxU2xkU09WRkRNazQzVFV0SFVWWkhWbEZYTVVWTFNFeEZNa2hOTWpsSU5GZEdRbEJWTTFBMFMxTkZVRFE1VVVkRlFrOUZPVnBOVlRGVU5nPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
