apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-with-argocd
spec:
  inputs:
    params:
      - default: '--'
        name: FLAGS
        type: string
      - default: 'develop'
        name: ENVIRONMENT
        type: string
      - name: LAYER
        type: string
      - name: argocd-version
        default: v1.3.0
        type: string
    resources:
      - name: image
        type: image
  stepTemplate:
    envFrom:
      - secretRef:
          name: argocd-env-secret
    name: ''
    resources: {}
  steps:
    - image: 'quay.io/rshop/toolchain-cli-alpine:v0.1'
      name: get-manifest
      resources: {}
      script: |
        REPOSITORY="$(echo "$(inputs.resources.image.url)" | sed 's/quay.io\///')"
        echo "$(curl -s "https://quay.io/api/v1/repository/$REPOSITORY/tag/?onlyActiveTags=true&specificTag=$(inputs.params.ENVIRONMENT)" | jq -r '.tags[0].manifest_digest')" | tee manifest
      workingDir: /workspace
    - name: login
      image: argoproj/argocd:$(params.argocd-version)
      script: |
        if [ -z $ARGOCD_AUTH_TOKEN ]; then
          yes | argocd login $ARGOCD_SERVER --username=$ARGOCD_USERNAME --password=$ARGOCD_PASSWORD $(inputs.params.FLAGS);
        fi
    - script: |
        export MANIFEST="$(cat manifest)"
        argocd app set "$(inputs.params.LAYER)-$(inputs.params.ENVIRONMENT)" -p image.manifest="$(inputs.resources.image.url)@$MANIFEST" --project my-turn-app $(inputs.params.FLAGS)
      image: argoproj/argocd:$(params.argocd-version)
      name: set-new-manifest
      workingDir: /workspace
      resources: {}
    - args:
        - >-
          argocd app sync "$(inputs.params.LAYER)-$(inputs.params.ENVIRONMENT)" --revision $(inputs.params.ENVIRONMENT) --project my-turn-app $(inputs.params.FLAGS)
      command:
        - /bin/bash
        - '-c'
      image: argoproj/argocd:$(params.argocd-version)
      name: sync-configurations
      resources: {}
    - args:
        - argocd app wait "$(inputs.params.LAYER)-$(inputs.params.ENVIRONMENT)" --health --project my-turn-app $(inputs.params.FLAGS)
      command:
        - /bin/bash
        - '-c'
      image: argoproj/argocd:$(params.argocd-version)
      name: wait
      resources: {}
