apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-backend-image
spec:
  inputs:
    params:
      - description: git url to clone
        name: url
        type: string
      - default: master
        description: 'git revision to checkout (branch, tag, sha, ref…)'
        name: revision
        type: string
  steps:
    - image: 'quay.io/rshop/toolchain-cli-alpine:master'
      name: clone-code
      resources: {}
      script: >
        #!/usr/bin/env sh

        git clone --branch "$(inputs.params.revision)" "$(inputs.params.url)"
        /src/tmp-code

        cp -r /src/tmp-code/* /src/my-turn-app

        cd /src/tmp-code/

        git show-branch --current

        tree -L 1 /src/my-turn-app/backend
      volumeMounts:
        - mountPath: /src
          name: source-code
    - image: 'quay.io/rshop/npm-alpine:master'
      name: test-lint-and-build
      resources: {}
      script: |
        #!/usr/bin/env sh
        cd /src/my-turn-app/backend
        npm install
        npm run test
      volumeMounts:
        - mountPath: /src
          name: source-code
    - args:
        - '--dockerfile=/src/my-turn-app/backend/Dockerfile'
        - '--context=dir:///src/my-turn-app/backend'
        - '--destination=quay.io/rshop/my-turn-app-backend:develop'
      image: 'gcr.io/kaniko-project/executor:latest'
      name: generate-and-push-image
      resources: {}
      securityContext:
        runAsUser: 0
      volumeMounts:
        - mountPath: /kaniko/.docker
          name: docker-config-volume
        - mountPath: /root/.docker
          name: docker-config-volume
        - mountPath: /src
          name: source-code
  volumes:
    - emptyDir: {}
      name: source-code
    - name: docker-config-volume
      secret:
        secretName: rshop-registry-auth
  workspaces:
    - description: The node packages needed for this app
      mountPath: /src/my-turn-app/backend/node_modules
      name: npm-modules
